addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bc
language: node_js
node_js:
- node
- '10'
- '8'
- '6'
sudo: false
cache:
  directories:
  - node_modules
  - website/node_modules
env:
  global:
  - secure: c4unKozz+OKffwUmypDb+E8qcR9JM7tb7fQ75jidOiz57HM5hmLVJokj017GrUeoPAw3nSE6l0O9Yvyf5K4QNguZ4IXlrtTO1repPLHyUCX3Hoo3PhXDo6g6ySpt8tMpP3dX6r7JUn5YHjxASfOI8VJTmcnxyNkVH66H6VMOA2I=
  - secure: hXK6PKQeWCX+5mzelq5/UpnAa4Z3oS3Ke/Rs93EHNcgJ6Bnb2Zu74wj8aEN3weAijg3+1KVbGJczvHKDXTQlqh5Xy4Ihwog3Rn3l1geySBCn/qfyWAWvTL0/wpWe8JyXxlsYiGFI2J4VM16FQ2cSXxhuAOWXlHrqyP2G8IR2Nmk=
  - secure: ZI8VPRHs1q7beGHvumEAKHYEt3NGhghNAVzl8U6YsshU44/oZziFMPf3rNj2CTcILIIDZksh5hg3VW1Rnnk606bS1DYKootwTeCu0r2eNAG7WWoiZZEB1kIBXrqxBFl8FDmcqaXRRcFlEn8vKd3JGIF06ehSMqCWC3g1/HJ7ZgY=
script:
- if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 4")" -eq 1 ]; then npm run lint; fi
- npm run build
- npm run test
- npm run website:install
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/travis-deploy.sh
  on:
    branch: master
    node: '10'
